name: Get statistics of music sessions

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  downloadTodayMusicSession:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js version 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Download today music session
        run: npm run get-today-music-sessions
        env:
          youtubeApiKey: ${{ secrets.YOUTUBE_API_KEY }}

      - name: Publishing data
        run: |
          git config user.name javlop-pipeline-bot
          git config user.email kmkzberzerk@gmail.com
          git add .
          git commit -m "chore: add new music session"
          git push

  getVideoStatistics:
    needs: downloadAndPublish
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js version 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Get statistics of the videos
        run: npm run get-videos-statistics
        env:
          youtubeApiKey: ${{ secrets.YOUTUBE_API_KEY }}

      - name: Publishing data
        run: |
          git config user.name javlop-pipeline-bot
          git config user.email kmkzberzerk@gmail.com
          git add .
          git commit -m "chore: add statistics for today"
          git push
